root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "./tmp/api"
args_bin = ["api"]
cmd = "go build -o ./tmp/api cmd/swiss/swiss.go"
delay = 1500
include_dir = [
  "api", "eve/runtime","core/runtime",
  "base", "ent",
  "ogent",
  "cmd/server",
  "cmd/swiss",
  "graph",
]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "gen-openapi.sh",
  "local",
  "readme.md",
  "web",
  "web-src",
  "testdata",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
kill_delay = "0.2s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
