// Code generated by ent, DO NOT EDIT.

package core

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"freefrom.space/nobot/core/botevents"
	"freefrom.space/nobot/core/internal"
	"freefrom.space/nobot/core/predicate"
)

// BotEventsQuery is the builder for querying BotEvents entities.
type BotEventsQuery struct {
	config
	ctx        *QueryContext
	order      []botevents.OrderOption
	inters     []Interceptor
	predicates []predicate.BotEvents
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BotEventsQuery builder.
func (beq *BotEventsQuery) Where(ps ...predicate.BotEvents) *BotEventsQuery {
	beq.predicates = append(beq.predicates, ps...)
	return beq
}

// Limit the number of records to be returned by this query.
func (beq *BotEventsQuery) Limit(limit int) *BotEventsQuery {
	beq.ctx.Limit = &limit
	return beq
}

// Offset to start from.
func (beq *BotEventsQuery) Offset(offset int) *BotEventsQuery {
	beq.ctx.Offset = &offset
	return beq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (beq *BotEventsQuery) Unique(unique bool) *BotEventsQuery {
	beq.ctx.Unique = &unique
	return beq
}

// Order specifies how the records should be ordered.
func (beq *BotEventsQuery) Order(o ...botevents.OrderOption) *BotEventsQuery {
	beq.order = append(beq.order, o...)
	return beq
}

// First returns the first BotEvents entity from the query.
// Returns a *NotFoundError when no BotEvents was found.
func (beq *BotEventsQuery) First(ctx context.Context) (*BotEvents, error) {
	nodes, err := beq.Limit(1).All(setContextOp(ctx, beq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{botevents.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (beq *BotEventsQuery) FirstX(ctx context.Context) *BotEvents {
	node, err := beq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BotEvents ID from the query.
// Returns a *NotFoundError when no BotEvents ID was found.
func (beq *BotEventsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = beq.Limit(1).IDs(setContextOp(ctx, beq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{botevents.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (beq *BotEventsQuery) FirstIDX(ctx context.Context) int {
	id, err := beq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BotEvents entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BotEvents entity is found.
// Returns a *NotFoundError when no BotEvents entities are found.
func (beq *BotEventsQuery) Only(ctx context.Context) (*BotEvents, error) {
	nodes, err := beq.Limit(2).All(setContextOp(ctx, beq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{botevents.Label}
	default:
		return nil, &NotSingularError{botevents.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (beq *BotEventsQuery) OnlyX(ctx context.Context) *BotEvents {
	node, err := beq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BotEvents ID in the query.
// Returns a *NotSingularError when more than one BotEvents ID is found.
// Returns a *NotFoundError when no entities are found.
func (beq *BotEventsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = beq.Limit(2).IDs(setContextOp(ctx, beq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{botevents.Label}
	default:
		err = &NotSingularError{botevents.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (beq *BotEventsQuery) OnlyIDX(ctx context.Context) int {
	id, err := beq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BotEventsSlice.
func (beq *BotEventsQuery) All(ctx context.Context) ([]*BotEvents, error) {
	ctx = setContextOp(ctx, beq.ctx, "All")
	if err := beq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BotEvents, *BotEventsQuery]()
	return withInterceptors[[]*BotEvents](ctx, beq, qr, beq.inters)
}

// AllX is like All, but panics if an error occurs.
func (beq *BotEventsQuery) AllX(ctx context.Context) []*BotEvents {
	nodes, err := beq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BotEvents IDs.
func (beq *BotEventsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if beq.ctx.Unique == nil && beq.path != nil {
		beq.Unique(true)
	}
	ctx = setContextOp(ctx, beq.ctx, "IDs")
	if err = beq.Select(botevents.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (beq *BotEventsQuery) IDsX(ctx context.Context) []int {
	ids, err := beq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (beq *BotEventsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, beq.ctx, "Count")
	if err := beq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, beq, querierCount[*BotEventsQuery](), beq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (beq *BotEventsQuery) CountX(ctx context.Context) int {
	count, err := beq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (beq *BotEventsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, beq.ctx, "Exist")
	switch _, err := beq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("core: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (beq *BotEventsQuery) ExistX(ctx context.Context) bool {
	exist, err := beq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BotEventsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (beq *BotEventsQuery) Clone() *BotEventsQuery {
	if beq == nil {
		return nil
	}
	return &BotEventsQuery{
		config:     beq.config,
		ctx:        beq.ctx.Clone(),
		order:      append([]botevents.OrderOption{}, beq.order...),
		inters:     append([]Interceptor{}, beq.inters...),
		predicates: append([]predicate.BotEvents{}, beq.predicates...),
		// clone intermediate query.
		sql:  beq.sql.Clone(),
		path: beq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BotEvents.Query().
//		GroupBy(botevents.FieldEventID).
//		Aggregate(core.Count()).
//		Scan(ctx, &v)
func (beq *BotEventsQuery) GroupBy(field string, fields ...string) *BotEventsGroupBy {
	beq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BotEventsGroupBy{build: beq}
	grbuild.flds = &beq.ctx.Fields
	grbuild.label = botevents.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//	}
//
//	client.BotEvents.Query().
//		Select(botevents.FieldEventID).
//		Scan(ctx, &v)
func (beq *BotEventsQuery) Select(fields ...string) *BotEventsSelect {
	beq.ctx.Fields = append(beq.ctx.Fields, fields...)
	sbuild := &BotEventsSelect{BotEventsQuery: beq}
	sbuild.label = botevents.Label
	sbuild.flds, sbuild.scan = &beq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BotEventsSelect configured with the given aggregations.
func (beq *BotEventsQuery) Aggregate(fns ...AggregateFunc) *BotEventsSelect {
	return beq.Select().Aggregate(fns...)
}

func (beq *BotEventsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range beq.inters {
		if inter == nil {
			return fmt.Errorf("core: uninitialized interceptor (forgotten import core/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, beq); err != nil {
				return err
			}
		}
	}
	for _, f := range beq.ctx.Fields {
		if !botevents.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("core: invalid field %q for query", f)}
		}
	}
	if beq.path != nil {
		prev, err := beq.path(ctx)
		if err != nil {
			return err
		}
		beq.sql = prev
	}
	return nil
}

func (beq *BotEventsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BotEvents, error) {
	var (
		nodes = []*BotEvents{}
		_spec = beq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BotEvents).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BotEvents{config: beq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = beq.schemaConfig.BotEvents
	ctx = internal.NewSchemaConfigContext(ctx, beq.schemaConfig)
	if len(beq.modifiers) > 0 {
		_spec.Modifiers = beq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, beq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (beq *BotEventsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := beq.querySpec()
	_spec.Node.Schema = beq.schemaConfig.BotEvents
	ctx = internal.NewSchemaConfigContext(ctx, beq.schemaConfig)
	if len(beq.modifiers) > 0 {
		_spec.Modifiers = beq.modifiers
	}
	_spec.Node.Columns = beq.ctx.Fields
	if len(beq.ctx.Fields) > 0 {
		_spec.Unique = beq.ctx.Unique != nil && *beq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, beq.driver, _spec)
}

func (beq *BotEventsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(botevents.Table, botevents.Columns, sqlgraph.NewFieldSpec(botevents.FieldID, field.TypeInt))
	_spec.From = beq.sql
	if unique := beq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if beq.path != nil {
		_spec.Unique = true
	}
	if fields := beq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, botevents.FieldID)
		for i := range fields {
			if fields[i] != botevents.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := beq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := beq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := beq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := beq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (beq *BotEventsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(beq.driver.Dialect())
	t1 := builder.Table(botevents.Table)
	columns := beq.ctx.Fields
	if len(columns) == 0 {
		columns = botevents.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if beq.sql != nil {
		selector = beq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if beq.ctx.Unique != nil && *beq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(beq.schemaConfig.BotEvents)
	ctx = internal.NewSchemaConfigContext(ctx, beq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range beq.modifiers {
		m(selector)
	}
	for _, p := range beq.predicates {
		p(selector)
	}
	for _, p := range beq.order {
		p(selector)
	}
	if offset := beq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := beq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (beq *BotEventsQuery) ForUpdate(opts ...sql.LockOption) *BotEventsQuery {
	if beq.driver.Dialect() == dialect.Postgres {
		beq.Unique(false)
	}
	beq.modifiers = append(beq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return beq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (beq *BotEventsQuery) ForShare(opts ...sql.LockOption) *BotEventsQuery {
	if beq.driver.Dialect() == dialect.Postgres {
		beq.Unique(false)
	}
	beq.modifiers = append(beq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return beq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (beq *BotEventsQuery) Modify(modifiers ...func(s *sql.Selector)) *BotEventsSelect {
	beq.modifiers = append(beq.modifiers, modifiers...)
	return beq.Select()
}

// BotEventsGroupBy is the group-by builder for BotEvents entities.
type BotEventsGroupBy struct {
	selector
	build *BotEventsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (begb *BotEventsGroupBy) Aggregate(fns ...AggregateFunc) *BotEventsGroupBy {
	begb.fns = append(begb.fns, fns...)
	return begb
}

// Scan applies the selector query and scans the result into the given value.
func (begb *BotEventsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, begb.build.ctx, "GroupBy")
	if err := begb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BotEventsQuery, *BotEventsGroupBy](ctx, begb.build, begb, begb.build.inters, v)
}

func (begb *BotEventsGroupBy) sqlScan(ctx context.Context, root *BotEventsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(begb.fns))
	for _, fn := range begb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*begb.flds)+len(begb.fns))
		for _, f := range *begb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*begb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := begb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BotEventsSelect is the builder for selecting fields of BotEvents entities.
type BotEventsSelect struct {
	*BotEventsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bes *BotEventsSelect) Aggregate(fns ...AggregateFunc) *BotEventsSelect {
	bes.fns = append(bes.fns, fns...)
	return bes
}

// Scan applies the selector query and scans the result into the given value.
func (bes *BotEventsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bes.ctx, "Select")
	if err := bes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BotEventsQuery, *BotEventsSelect](ctx, bes.BotEventsQuery, bes, bes.inters, v)
}

func (bes *BotEventsSelect) sqlScan(ctx context.Context, root *BotEventsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bes.fns))
	for _, fn := range bes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bes *BotEventsSelect) Modify(modifiers ...func(s *sql.Selector)) *BotEventsSelect {
	bes.modifiers = append(bes.modifiers, modifiers...)
	return bes
}
