// Code generated by ent, DO NOT EDIT.

package core

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"freefrom.space/nobot/core/internal"
	"freefrom.space/nobot/core/nostrnotesfetchhistory"
	"freefrom.space/nobot/core/predicate"
)

// NostrNotesFetchHistoryQuery is the builder for querying NostrNotesFetchHistory entities.
type NostrNotesFetchHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []nostrnotesfetchhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.NostrNotesFetchHistory
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NostrNotesFetchHistoryQuery builder.
func (nnfhq *NostrNotesFetchHistoryQuery) Where(ps ...predicate.NostrNotesFetchHistory) *NostrNotesFetchHistoryQuery {
	nnfhq.predicates = append(nnfhq.predicates, ps...)
	return nnfhq
}

// Limit the number of records to be returned by this query.
func (nnfhq *NostrNotesFetchHistoryQuery) Limit(limit int) *NostrNotesFetchHistoryQuery {
	nnfhq.ctx.Limit = &limit
	return nnfhq
}

// Offset to start from.
func (nnfhq *NostrNotesFetchHistoryQuery) Offset(offset int) *NostrNotesFetchHistoryQuery {
	nnfhq.ctx.Offset = &offset
	return nnfhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nnfhq *NostrNotesFetchHistoryQuery) Unique(unique bool) *NostrNotesFetchHistoryQuery {
	nnfhq.ctx.Unique = &unique
	return nnfhq
}

// Order specifies how the records should be ordered.
func (nnfhq *NostrNotesFetchHistoryQuery) Order(o ...nostrnotesfetchhistory.OrderOption) *NostrNotesFetchHistoryQuery {
	nnfhq.order = append(nnfhq.order, o...)
	return nnfhq
}

// First returns the first NostrNotesFetchHistory entity from the query.
// Returns a *NotFoundError when no NostrNotesFetchHistory was found.
func (nnfhq *NostrNotesFetchHistoryQuery) First(ctx context.Context) (*NostrNotesFetchHistory, error) {
	nodes, err := nnfhq.Limit(1).All(setContextOp(ctx, nnfhq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nostrnotesfetchhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) FirstX(ctx context.Context) *NostrNotesFetchHistory {
	node, err := nnfhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NostrNotesFetchHistory ID from the query.
// Returns a *NotFoundError when no NostrNotesFetchHistory ID was found.
func (nnfhq *NostrNotesFetchHistoryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = nnfhq.Limit(1).IDs(setContextOp(ctx, nnfhq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nostrnotesfetchhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) FirstIDX(ctx context.Context) string {
	id, err := nnfhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NostrNotesFetchHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NostrNotesFetchHistory entity is found.
// Returns a *NotFoundError when no NostrNotesFetchHistory entities are found.
func (nnfhq *NostrNotesFetchHistoryQuery) Only(ctx context.Context) (*NostrNotesFetchHistory, error) {
	nodes, err := nnfhq.Limit(2).All(setContextOp(ctx, nnfhq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nostrnotesfetchhistory.Label}
	default:
		return nil, &NotSingularError{nostrnotesfetchhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) OnlyX(ctx context.Context) *NostrNotesFetchHistory {
	node, err := nnfhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NostrNotesFetchHistory ID in the query.
// Returns a *NotSingularError when more than one NostrNotesFetchHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (nnfhq *NostrNotesFetchHistoryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = nnfhq.Limit(2).IDs(setContextOp(ctx, nnfhq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nostrnotesfetchhistory.Label}
	default:
		err = &NotSingularError{nostrnotesfetchhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) OnlyIDX(ctx context.Context) string {
	id, err := nnfhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NostrNotesFetchHistories.
func (nnfhq *NostrNotesFetchHistoryQuery) All(ctx context.Context) ([]*NostrNotesFetchHistory, error) {
	ctx = setContextOp(ctx, nnfhq.ctx, "All")
	if err := nnfhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NostrNotesFetchHistory, *NostrNotesFetchHistoryQuery]()
	return withInterceptors[[]*NostrNotesFetchHistory](ctx, nnfhq, qr, nnfhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) AllX(ctx context.Context) []*NostrNotesFetchHistory {
	nodes, err := nnfhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NostrNotesFetchHistory IDs.
func (nnfhq *NostrNotesFetchHistoryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if nnfhq.ctx.Unique == nil && nnfhq.path != nil {
		nnfhq.Unique(true)
	}
	ctx = setContextOp(ctx, nnfhq.ctx, "IDs")
	if err = nnfhq.Select(nostrnotesfetchhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) IDsX(ctx context.Context) []string {
	ids, err := nnfhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nnfhq *NostrNotesFetchHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nnfhq.ctx, "Count")
	if err := nnfhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nnfhq, querierCount[*NostrNotesFetchHistoryQuery](), nnfhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) CountX(ctx context.Context) int {
	count, err := nnfhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nnfhq *NostrNotesFetchHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nnfhq.ctx, "Exist")
	switch _, err := nnfhq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("core: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nnfhq *NostrNotesFetchHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := nnfhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NostrNotesFetchHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nnfhq *NostrNotesFetchHistoryQuery) Clone() *NostrNotesFetchHistoryQuery {
	if nnfhq == nil {
		return nil
	}
	return &NostrNotesFetchHistoryQuery{
		config:     nnfhq.config,
		ctx:        nnfhq.ctx.Clone(),
		order:      append([]nostrnotesfetchhistory.OrderOption{}, nnfhq.order...),
		inters:     append([]Interceptor{}, nnfhq.inters...),
		predicates: append([]predicate.NostrNotesFetchHistory{}, nnfhq.predicates...),
		// clone intermediate query.
		sql:  nnfhq.sql.Clone(),
		path: nnfhq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PublishAt time.Time `json:"publish_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NostrNotesFetchHistory.Query().
//		GroupBy(nostrnotesfetchhistory.FieldPublishAt).
//		Aggregate(core.Count()).
//		Scan(ctx, &v)
func (nnfhq *NostrNotesFetchHistoryQuery) GroupBy(field string, fields ...string) *NostrNotesFetchHistoryGroupBy {
	nnfhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NostrNotesFetchHistoryGroupBy{build: nnfhq}
	grbuild.flds = &nnfhq.ctx.Fields
	grbuild.label = nostrnotesfetchhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PublishAt time.Time `json:"publish_at,omitempty"`
//	}
//
//	client.NostrNotesFetchHistory.Query().
//		Select(nostrnotesfetchhistory.FieldPublishAt).
//		Scan(ctx, &v)
func (nnfhq *NostrNotesFetchHistoryQuery) Select(fields ...string) *NostrNotesFetchHistorySelect {
	nnfhq.ctx.Fields = append(nnfhq.ctx.Fields, fields...)
	sbuild := &NostrNotesFetchHistorySelect{NostrNotesFetchHistoryQuery: nnfhq}
	sbuild.label = nostrnotesfetchhistory.Label
	sbuild.flds, sbuild.scan = &nnfhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NostrNotesFetchHistorySelect configured with the given aggregations.
func (nnfhq *NostrNotesFetchHistoryQuery) Aggregate(fns ...AggregateFunc) *NostrNotesFetchHistorySelect {
	return nnfhq.Select().Aggregate(fns...)
}

func (nnfhq *NostrNotesFetchHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nnfhq.inters {
		if inter == nil {
			return fmt.Errorf("core: uninitialized interceptor (forgotten import core/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nnfhq); err != nil {
				return err
			}
		}
	}
	for _, f := range nnfhq.ctx.Fields {
		if !nostrnotesfetchhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("core: invalid field %q for query", f)}
		}
	}
	if nnfhq.path != nil {
		prev, err := nnfhq.path(ctx)
		if err != nil {
			return err
		}
		nnfhq.sql = prev
	}
	return nil
}

func (nnfhq *NostrNotesFetchHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NostrNotesFetchHistory, error) {
	var (
		nodes = []*NostrNotesFetchHistory{}
		_spec = nnfhq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NostrNotesFetchHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NostrNotesFetchHistory{config: nnfhq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = nnfhq.schemaConfig.NostrNotesFetchHistory
	ctx = internal.NewSchemaConfigContext(ctx, nnfhq.schemaConfig)
	if len(nnfhq.modifiers) > 0 {
		_spec.Modifiers = nnfhq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nnfhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nnfhq *NostrNotesFetchHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nnfhq.querySpec()
	_spec.Node.Schema = nnfhq.schemaConfig.NostrNotesFetchHistory
	ctx = internal.NewSchemaConfigContext(ctx, nnfhq.schemaConfig)
	if len(nnfhq.modifiers) > 0 {
		_spec.Modifiers = nnfhq.modifiers
	}
	_spec.Node.Columns = nnfhq.ctx.Fields
	if len(nnfhq.ctx.Fields) > 0 {
		_spec.Unique = nnfhq.ctx.Unique != nil && *nnfhq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nnfhq.driver, _spec)
}

func (nnfhq *NostrNotesFetchHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nostrnotesfetchhistory.Table, nostrnotesfetchhistory.Columns, sqlgraph.NewFieldSpec(nostrnotesfetchhistory.FieldID, field.TypeString))
	_spec.From = nnfhq.sql
	if unique := nnfhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nnfhq.path != nil {
		_spec.Unique = true
	}
	if fields := nnfhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nostrnotesfetchhistory.FieldID)
		for i := range fields {
			if fields[i] != nostrnotesfetchhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nnfhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nnfhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nnfhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nnfhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nnfhq *NostrNotesFetchHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nnfhq.driver.Dialect())
	t1 := builder.Table(nostrnotesfetchhistory.Table)
	columns := nnfhq.ctx.Fields
	if len(columns) == 0 {
		columns = nostrnotesfetchhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nnfhq.sql != nil {
		selector = nnfhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nnfhq.ctx.Unique != nil && *nnfhq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(nnfhq.schemaConfig.NostrNotesFetchHistory)
	ctx = internal.NewSchemaConfigContext(ctx, nnfhq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range nnfhq.modifiers {
		m(selector)
	}
	for _, p := range nnfhq.predicates {
		p(selector)
	}
	for _, p := range nnfhq.order {
		p(selector)
	}
	if offset := nnfhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nnfhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (nnfhq *NostrNotesFetchHistoryQuery) ForUpdate(opts ...sql.LockOption) *NostrNotesFetchHistoryQuery {
	if nnfhq.driver.Dialect() == dialect.Postgres {
		nnfhq.Unique(false)
	}
	nnfhq.modifiers = append(nnfhq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return nnfhq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (nnfhq *NostrNotesFetchHistoryQuery) ForShare(opts ...sql.LockOption) *NostrNotesFetchHistoryQuery {
	if nnfhq.driver.Dialect() == dialect.Postgres {
		nnfhq.Unique(false)
	}
	nnfhq.modifiers = append(nnfhq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return nnfhq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nnfhq *NostrNotesFetchHistoryQuery) Modify(modifiers ...func(s *sql.Selector)) *NostrNotesFetchHistorySelect {
	nnfhq.modifiers = append(nnfhq.modifiers, modifiers...)
	return nnfhq.Select()
}

// NostrNotesFetchHistoryGroupBy is the group-by builder for NostrNotesFetchHistory entities.
type NostrNotesFetchHistoryGroupBy struct {
	selector
	build *NostrNotesFetchHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nnfhgb *NostrNotesFetchHistoryGroupBy) Aggregate(fns ...AggregateFunc) *NostrNotesFetchHistoryGroupBy {
	nnfhgb.fns = append(nnfhgb.fns, fns...)
	return nnfhgb
}

// Scan applies the selector query and scans the result into the given value.
func (nnfhgb *NostrNotesFetchHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nnfhgb.build.ctx, "GroupBy")
	if err := nnfhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NostrNotesFetchHistoryQuery, *NostrNotesFetchHistoryGroupBy](ctx, nnfhgb.build, nnfhgb, nnfhgb.build.inters, v)
}

func (nnfhgb *NostrNotesFetchHistoryGroupBy) sqlScan(ctx context.Context, root *NostrNotesFetchHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nnfhgb.fns))
	for _, fn := range nnfhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nnfhgb.flds)+len(nnfhgb.fns))
		for _, f := range *nnfhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nnfhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nnfhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NostrNotesFetchHistorySelect is the builder for selecting fields of NostrNotesFetchHistory entities.
type NostrNotesFetchHistorySelect struct {
	*NostrNotesFetchHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nnfhs *NostrNotesFetchHistorySelect) Aggregate(fns ...AggregateFunc) *NostrNotesFetchHistorySelect {
	nnfhs.fns = append(nnfhs.fns, fns...)
	return nnfhs
}

// Scan applies the selector query and scans the result into the given value.
func (nnfhs *NostrNotesFetchHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nnfhs.ctx, "Select")
	if err := nnfhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NostrNotesFetchHistoryQuery, *NostrNotesFetchHistorySelect](ctx, nnfhs.NostrNotesFetchHistoryQuery, nnfhs, nnfhs.inters, v)
}

func (nnfhs *NostrNotesFetchHistorySelect) sqlScan(ctx context.Context, root *NostrNotesFetchHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nnfhs.fns))
	for _, fn := range nnfhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nnfhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nnfhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nnfhs *NostrNotesFetchHistorySelect) Modify(modifiers ...func(s *sql.Selector)) *NostrNotesFetchHistorySelect {
	nnfhs.modifiers = append(nnfhs.modifiers, modifiers...)
	return nnfhs
}
