// Code generated by ent, DO NOT EDIT.

package core

import (
	"time"

	"freefrom.space/nobot/core/events"
	"freefrom.space/nobot/core/nostrnotesfetchhistory"
	"freefrom.space/nobot/core/schema"
	"freefrom.space/nobot/core/twitterfetchhistory"
	"freefrom.space/nobot/core/twitternote"
	"freefrom.space/nobot/core/twitterprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventsFields := schema.Events{}.Fields()
	_ = eventsFields
	// eventsDescTags is the schema descriptor for tags field.
	eventsDescTags := eventsFields[6].Descriptor()
	// events.DefaultTags holds the default value on creation for the tags field.
	events.DefaultTags = eventsDescTags.Default.([][]string)
	// eventsDescContent is the schema descriptor for content field.
	eventsDescContent := eventsFields[7].Descriptor()
	// events.DefaultContent holds the default value on creation for the content field.
	events.DefaultContent = eventsDescContent.Default.(string)
	nostrnotesfetchhistoryFields := schema.NostrNotesFetchHistory{}.Fields()
	_ = nostrnotesfetchhistoryFields
	// nostrnotesfetchhistoryDescID is the schema descriptor for id field.
	nostrnotesfetchhistoryDescID := nostrnotesfetchhistoryFields[0].Descriptor()
	// nostrnotesfetchhistory.IDValidator is a validator for the "id" field. It is called by the builders before save.
	nostrnotesfetchhistory.IDValidator = nostrnotesfetchhistoryDescID.Validators[0].(func(string) error)
	twitterfetchhistoryFields := schema.TwitterFetchHistory{}.Fields()
	_ = twitterfetchhistoryFields
	// twitterfetchhistoryDescFetchAt is the schema descriptor for fetch_at field.
	twitterfetchhistoryDescFetchAt := twitterfetchhistoryFields[3].Descriptor()
	// twitterfetchhistory.DefaultFetchAt holds the default value on creation for the fetch_at field.
	twitterfetchhistory.DefaultFetchAt = twitterfetchhistoryDescFetchAt.Default.(func() time.Time)
	twitternoteFields := schema.TwitterNote{}.Fields()
	_ = twitternoteFields
	// twitternoteDescLanguage is the schema descriptor for language field.
	twitternoteDescLanguage := twitternoteFields[34].Descriptor()
	// twitternote.DefaultLanguage holds the default value on creation for the language field.
	twitternote.DefaultLanguage = twitternoteDescLanguage.Default.(string)
	twitterprofileFields := schema.TwitterProfile{}.Fields()
	_ = twitterprofileFields
	// twitterprofileDescPublishNostr is the schema descriptor for publish_nostr field.
	twitterprofileDescPublishNostr := twitterprofileFields[24].Descriptor()
	// twitterprofile.DefaultPublishNostr holds the default value on creation for the publish_nostr field.
	twitterprofile.DefaultPublishNostr = twitterprofileDescPublishNostr.Default.(bool)
}
