// Code generated by ent, DO NOT EDIT.

package core

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"freefrom.space/nobot/core/internal"
	"freefrom.space/nobot/core/predicate"
	"freefrom.space/nobot/core/twitterprofile"
)

// TwitterProfileQuery is the builder for querying TwitterProfile entities.
type TwitterProfileQuery struct {
	config
	ctx        *QueryContext
	order      []twitterprofile.OrderOption
	inters     []Interceptor
	predicates []predicate.TwitterProfile
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TwitterProfileQuery builder.
func (tpq *TwitterProfileQuery) Where(ps ...predicate.TwitterProfile) *TwitterProfileQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit the number of records to be returned by this query.
func (tpq *TwitterProfileQuery) Limit(limit int) *TwitterProfileQuery {
	tpq.ctx.Limit = &limit
	return tpq
}

// Offset to start from.
func (tpq *TwitterProfileQuery) Offset(offset int) *TwitterProfileQuery {
	tpq.ctx.Offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TwitterProfileQuery) Unique(unique bool) *TwitterProfileQuery {
	tpq.ctx.Unique = &unique
	return tpq
}

// Order specifies how the records should be ordered.
func (tpq *TwitterProfileQuery) Order(o ...twitterprofile.OrderOption) *TwitterProfileQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// First returns the first TwitterProfile entity from the query.
// Returns a *NotFoundError when no TwitterProfile was found.
func (tpq *TwitterProfileQuery) First(ctx context.Context) (*TwitterProfile, error) {
	nodes, err := tpq.Limit(1).All(setContextOp(ctx, tpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{twitterprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TwitterProfileQuery) FirstX(ctx context.Context) *TwitterProfile {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TwitterProfile ID from the query.
// Returns a *NotFoundError when no TwitterProfile ID was found.
func (tpq *TwitterProfileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(1).IDs(setContextOp(ctx, tpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{twitterprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TwitterProfileQuery) FirstIDX(ctx context.Context) int {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TwitterProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TwitterProfile entity is found.
// Returns a *NotFoundError when no TwitterProfile entities are found.
func (tpq *TwitterProfileQuery) Only(ctx context.Context) (*TwitterProfile, error) {
	nodes, err := tpq.Limit(2).All(setContextOp(ctx, tpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{twitterprofile.Label}
	default:
		return nil, &NotSingularError{twitterprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TwitterProfileQuery) OnlyX(ctx context.Context) *TwitterProfile {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TwitterProfile ID in the query.
// Returns a *NotSingularError when more than one TwitterProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TwitterProfileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(2).IDs(setContextOp(ctx, tpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{twitterprofile.Label}
	default:
		err = &NotSingularError{twitterprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TwitterProfileQuery) OnlyIDX(ctx context.Context) int {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TwitterProfiles.
func (tpq *TwitterProfileQuery) All(ctx context.Context) ([]*TwitterProfile, error) {
	ctx = setContextOp(ctx, tpq.ctx, "All")
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TwitterProfile, *TwitterProfileQuery]()
	return withInterceptors[[]*TwitterProfile](ctx, tpq, qr, tpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TwitterProfileQuery) AllX(ctx context.Context) []*TwitterProfile {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TwitterProfile IDs.
func (tpq *TwitterProfileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tpq.ctx.Unique == nil && tpq.path != nil {
		tpq.Unique(true)
	}
	ctx = setContextOp(ctx, tpq.ctx, "IDs")
	if err = tpq.Select(twitterprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TwitterProfileQuery) IDsX(ctx context.Context) []int {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TwitterProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tpq.ctx, "Count")
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tpq, querierCount[*TwitterProfileQuery](), tpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TwitterProfileQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TwitterProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tpq.ctx, "Exist")
	switch _, err := tpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("core: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TwitterProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TwitterProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TwitterProfileQuery) Clone() *TwitterProfileQuery {
	if tpq == nil {
		return nil
	}
	return &TwitterProfileQuery{
		config:     tpq.config,
		ctx:        tpq.ctx.Clone(),
		order:      append([]twitterprofile.OrderOption{}, tpq.order...),
		inters:     append([]Interceptor{}, tpq.inters...),
		predicates: append([]predicate.TwitterProfile{}, tpq.predicates...),
		// clone intermediate query.
		sql:  tpq.sql.Clone(),
		path: tpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TwitterProfile.Query().
//		GroupBy(twitterprofile.FieldUserID).
//		Aggregate(core.Count()).
//		Scan(ctx, &v)
func (tpq *TwitterProfileQuery) GroupBy(field string, fields ...string) *TwitterProfileGroupBy {
	tpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TwitterProfileGroupBy{build: tpq}
	grbuild.flds = &tpq.ctx.Fields
	grbuild.label = twitterprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.TwitterProfile.Query().
//		Select(twitterprofile.FieldUserID).
//		Scan(ctx, &v)
func (tpq *TwitterProfileQuery) Select(fields ...string) *TwitterProfileSelect {
	tpq.ctx.Fields = append(tpq.ctx.Fields, fields...)
	sbuild := &TwitterProfileSelect{TwitterProfileQuery: tpq}
	sbuild.label = twitterprofile.Label
	sbuild.flds, sbuild.scan = &tpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TwitterProfileSelect configured with the given aggregations.
func (tpq *TwitterProfileQuery) Aggregate(fns ...AggregateFunc) *TwitterProfileSelect {
	return tpq.Select().Aggregate(fns...)
}

func (tpq *TwitterProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tpq.inters {
		if inter == nil {
			return fmt.Errorf("core: uninitialized interceptor (forgotten import core/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tpq); err != nil {
				return err
			}
		}
	}
	for _, f := range tpq.ctx.Fields {
		if !twitterprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("core: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TwitterProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TwitterProfile, error) {
	var (
		nodes = []*TwitterProfile{}
		_spec = tpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TwitterProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TwitterProfile{config: tpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = tpq.schemaConfig.TwitterProfile
	ctx = internal.NewSchemaConfigContext(ctx, tpq.schemaConfig)
	if len(tpq.modifiers) > 0 {
		_spec.Modifiers = tpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tpq *TwitterProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	_spec.Node.Schema = tpq.schemaConfig.TwitterProfile
	ctx = internal.NewSchemaConfigContext(ctx, tpq.schemaConfig)
	if len(tpq.modifiers) > 0 {
		_spec.Modifiers = tpq.modifiers
	}
	_spec.Node.Columns = tpq.ctx.Fields
	if len(tpq.ctx.Fields) > 0 {
		_spec.Unique = tpq.ctx.Unique != nil && *tpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TwitterProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(twitterprofile.Table, twitterprofile.Columns, sqlgraph.NewFieldSpec(twitterprofile.FieldID, field.TypeInt))
	_spec.From = tpq.sql
	if unique := tpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tpq.path != nil {
		_spec.Unique = true
	}
	if fields := tpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, twitterprofile.FieldID)
		for i := range fields {
			if fields[i] != twitterprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TwitterProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(twitterprofile.Table)
	columns := tpq.ctx.Fields
	if len(columns) == 0 {
		columns = twitterprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tpq.ctx.Unique != nil && *tpq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(tpq.schemaConfig.TwitterProfile)
	ctx = internal.NewSchemaConfigContext(ctx, tpq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range tpq.modifiers {
		m(selector)
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tpq *TwitterProfileQuery) ForUpdate(opts ...sql.LockOption) *TwitterProfileQuery {
	if tpq.driver.Dialect() == dialect.Postgres {
		tpq.Unique(false)
	}
	tpq.modifiers = append(tpq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tpq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tpq *TwitterProfileQuery) ForShare(opts ...sql.LockOption) *TwitterProfileQuery {
	if tpq.driver.Dialect() == dialect.Postgres {
		tpq.Unique(false)
	}
	tpq.modifiers = append(tpq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tpq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tpq *TwitterProfileQuery) Modify(modifiers ...func(s *sql.Selector)) *TwitterProfileSelect {
	tpq.modifiers = append(tpq.modifiers, modifiers...)
	return tpq.Select()
}

// TwitterProfileGroupBy is the group-by builder for TwitterProfile entities.
type TwitterProfileGroupBy struct {
	selector
	build *TwitterProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TwitterProfileGroupBy) Aggregate(fns ...AggregateFunc) *TwitterProfileGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the selector query and scans the result into the given value.
func (tpgb *TwitterProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tpgb.build.ctx, "GroupBy")
	if err := tpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TwitterProfileQuery, *TwitterProfileGroupBy](ctx, tpgb.build, tpgb, tpgb.build.inters, v)
}

func (tpgb *TwitterProfileGroupBy) sqlScan(ctx context.Context, root *TwitterProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tpgb.flds)+len(tpgb.fns))
		for _, f := range *tpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TwitterProfileSelect is the builder for selecting fields of TwitterProfile entities.
type TwitterProfileSelect struct {
	*TwitterProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tps *TwitterProfileSelect) Aggregate(fns ...AggregateFunc) *TwitterProfileSelect {
	tps.fns = append(tps.fns, fns...)
	return tps
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TwitterProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tps.ctx, "Select")
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TwitterProfileQuery, *TwitterProfileSelect](ctx, tps.TwitterProfileQuery, tps, tps.inters, v)
}

func (tps *TwitterProfileSelect) sqlScan(ctx context.Context, root *TwitterProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tps.fns))
	for _, fn := range tps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tps *TwitterProfileSelect) Modify(modifiers ...func(s *sql.Selector)) *TwitterProfileSelect {
	tps.modifiers = append(tps.modifiers, modifiers...)
	return tps
}
