// Code generated by ent, DO NOT EDIT.

package core

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"freefrom.space/nobot/core/internal"
	"freefrom.space/nobot/core/predicate"
	"freefrom.space/nobot/core/twitternotesfetchhistory"
)

// TwitterNotesFetchHistoryDelete is the builder for deleting a TwitterNotesFetchHistory entity.
type TwitterNotesFetchHistoryDelete struct {
	config
	hooks    []Hook
	mutation *TwitterNotesFetchHistoryMutation
}

// Where appends a list predicates to the TwitterNotesFetchHistoryDelete builder.
func (tnfhd *TwitterNotesFetchHistoryDelete) Where(ps ...predicate.TwitterNotesFetchHistory) *TwitterNotesFetchHistoryDelete {
	tnfhd.mutation.Where(ps...)
	return tnfhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tnfhd *TwitterNotesFetchHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tnfhd.sqlExec, tnfhd.mutation, tnfhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tnfhd *TwitterNotesFetchHistoryDelete) ExecX(ctx context.Context) int {
	n, err := tnfhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tnfhd *TwitterNotesFetchHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(twitternotesfetchhistory.Table, sqlgraph.NewFieldSpec(twitternotesfetchhistory.FieldID, field.TypeInt64))
	_spec.Node.Schema = tnfhd.schemaConfig.TwitterNotesFetchHistory
	ctx = internal.NewSchemaConfigContext(ctx, tnfhd.schemaConfig)
	if ps := tnfhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tnfhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tnfhd.mutation.done = true
	return affected, err
}

// TwitterNotesFetchHistoryDeleteOne is the builder for deleting a single TwitterNotesFetchHistory entity.
type TwitterNotesFetchHistoryDeleteOne struct {
	tnfhd *TwitterNotesFetchHistoryDelete
}

// Where appends a list predicates to the TwitterNotesFetchHistoryDelete builder.
func (tnfhdo *TwitterNotesFetchHistoryDeleteOne) Where(ps ...predicate.TwitterNotesFetchHistory) *TwitterNotesFetchHistoryDeleteOne {
	tnfhdo.tnfhd.mutation.Where(ps...)
	return tnfhdo
}

// Exec executes the deletion query.
func (tnfhdo *TwitterNotesFetchHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := tnfhdo.tnfhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{twitternotesfetchhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tnfhdo *TwitterNotesFetchHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := tnfhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
