// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"freefrom.space/nobot/core"
)

// The BotEventsFunc type is an adapter to allow the use of ordinary
// function as BotEvents mutator.
type BotEventsFunc func(context.Context, *core.BotEventsMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f BotEventsFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.BotEventsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.BotEventsMutation", m)
}

// The EventsFunc type is an adapter to allow the use of ordinary
// function as Events mutator.
type EventsFunc func(context.Context, *core.EventsMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f EventsFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.EventsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.EventsMutation", m)
}

// The NostrNotesFetchHistoryFunc type is an adapter to allow the use of ordinary
// function as NostrNotesFetchHistory mutator.
type NostrNotesFetchHistoryFunc func(context.Context, *core.NostrNotesFetchHistoryMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f NostrNotesFetchHistoryFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.NostrNotesFetchHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.NostrNotesFetchHistoryMutation", m)
}

// The TwitterFetchHistoryFunc type is an adapter to allow the use of ordinary
// function as TwitterFetchHistory mutator.
type TwitterFetchHistoryFunc func(context.Context, *core.TwitterFetchHistoryMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f TwitterFetchHistoryFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.TwitterFetchHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.TwitterFetchHistoryMutation", m)
}

// The TwitterNoteFunc type is an adapter to allow the use of ordinary
// function as TwitterNote mutator.
type TwitterNoteFunc func(context.Context, *core.TwitterNoteMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f TwitterNoteFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.TwitterNoteMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.TwitterNoteMutation", m)
}

// The TwitterNotesFetchHistoryFunc type is an adapter to allow the use of ordinary
// function as TwitterNotesFetchHistory mutator.
type TwitterNotesFetchHistoryFunc func(context.Context, *core.TwitterNotesFetchHistoryMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f TwitterNotesFetchHistoryFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.TwitterNotesFetchHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.TwitterNotesFetchHistoryMutation", m)
}

// The TwitterProfileFunc type is an adapter to allow the use of ordinary
// function as TwitterProfile mutator.
type TwitterProfileFunc func(context.Context, *core.TwitterProfileMutation) (core.Value, error)

// Mutate calls f(ctx, m).
func (f TwitterProfileFunc) Mutate(ctx context.Context, m core.Mutation) (core.Value, error) {
	if mv, ok := m.(*core.TwitterProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *core.TwitterProfileMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, core.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m core.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m core.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m core.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op core.Op) Condition {
	return func(_ context.Context, m core.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m core.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m core.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m core.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk core.Hook, cond Condition) core.Hook {
	return func(next core.Mutator) core.Mutator {
		return core.MutateFunc(func(ctx context.Context, m core.Mutation) (core.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, core.Delete|core.Create)
func On(hk core.Hook, op core.Op) core.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, core.Update|core.UpdateOne)
func Unless(hk core.Hook, op core.Op) core.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) core.Hook {
	return func(core.Mutator) core.Mutator {
		return core.MutateFunc(func(context.Context, core.Mutation) (core.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []core.Hook {
//		return []core.Hook{
//			Reject(core.Delete|core.Update),
//		}
//	}
func Reject(op core.Op) core.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []core.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...core.Hook) Chain {
	return Chain{append([]core.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() core.Hook {
	return func(mutator core.Mutator) core.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...core.Hook) Chain {
	newHooks := make([]core.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
